### ISSUE TITLE
Add option to open video in mpv-android

### ISSUE THREAD

**Issue by aicynide** [iwestlin/gdshare#41]

**Comment by aicynide** [comment]
@iwestlin please look into this...

**Comment by iwestlin** [comment]
Hi, at first I thought it's impossible because I didn't find any URI scheme related to mpv-android, but after some digging I found https://github.com/mpv-android/mpv-android/issues/366#issuecomment-779752737

So we can construct link like `intent://mpv.io/images/mpv-logo-128-0baae5aa.png#Intent;type=video/any;package=is.xyz.mpv;scheme=https;end;` to call up mpv-android (tested successful

I'll push a new version to support this feature later, because I need to find the source code of this repo first😅

**Comment by iwestlin** [comment]
new version pushed: https://github.com/iwestlin/gdshare/commit/c9757fa929e748bddb5f48fa1daa81d3b241f5e3

you can replace `gdshare.20220310.js` with `gdshare.20230501.js` in template file to have this feature.

**Comment by aicynide** [comment]
Thank you very much kind sir
